name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
jobs:
  
  deploy:
  
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name : Deploy
      run: |
        sudo docker stop $(docker ps -a -q)
        sudo docker rm $(docker ps -a -q)
        echo "Deployed version:latest"
        sudo docker pull sbetancurb/to-do-app-1:latest
        sudo docker run -d -p 3000:3000 sbetancurb/to-do-app-1:latest
