name: CD 

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
jobs:
  
  deploy:
  
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name : Deploy
      run: |
        ./deploy.sh
        echo "Deployed version:latest"
        sudo docker pull sbetancurb/to-do-app-1:latest
        sudo docker run -d -p 8080:80 sbetancurb/to-do-app-1:latest
