name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Code
      uses: actions/checkout@v3

    - name: Build
      run: |
        sudo docker build -t sbetancur02/to-do-app ./app --tag sbetancurb/to-do-app-1:latest

  test:

    runs-on: self-hosted

    needs: build

    steps:
    - name: Code
      uses: actions/checkout@v2

    - name: Test
      run: sudo docker run sbetancur02/to-do-app npm test

  release:
  
    runs-on: self-hosted

    needs: test

    steps:
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
        DOCKER_PASS: ${{secrets.DOCKERHUB_PASS}}
      run: sudo docker login -u $DOCKER_USER -p $DOCKER_PASS

    - name: Docker Push
      run: sudo docker push sbetancurb/to-do-app-1

  deploy:
  
    runs-on: self-hosted

    needs: release

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name : Deploy
      run: |
        sudo ~/To-Do-App/app/deploy.sh
        echo "Deployed version:latest"
        sudo docker pull sbetancurb/to-do-app-1:latest
        sudo docker run -d -p 8080:80 sbetancurb/to-do-app-1:latest
  
