name: CI 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Code
      uses: actions/checkout@v3

    - name: Build
      run: docker build -t sbetancur02/to-do-app ./app --tag sbetancurb/to-do-app-1:latest

  test:

    runs-on: self-hosted

    needs: build

    steps:
    - name: Code
      uses: actions/checkout@v2

    - name: Test
      run: docker run sbetancur02/to-do-app npm test

  release:
  
    runs-on: self-hosted

    needs: test

    steps:
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
        DOCKER_PASS: ${{secrets.DOCKERHUB_PASS}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS

    - name: Docker Push
      run: docker push sbetancurb/to-do-app-1
