name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Code
      uses: actions/checkout@v3

    - name: Build
      run: docker buildx build -t sbetancur02/to-do-app ./app

  test:

    runs-on: self-hosted

    needs: build

    steps:
    - name: Code
      uses: actions/checkout@v2

    - name: Test
      run: docker run sbetancur02/to-do-app npm test

  release:
  
    runs-on: self-hosted

    needs: test

    steps:
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
        DOCKER_PASS: ${{secrets.DOCKERHUB_PASS}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sbetancurb/to-do-app-1:latest

    - name: Docker Push
      run: docker push sbetancurb/to-do-app-1

  deploy:
  
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name : Deploy
      run: |
        docker stop $(docker ps -a -q)
        docker rm $(docker ps -a -q)
        echo "Deployed version:latest"
        docker pull sbetancurb/to-do-app-1:latest
        docker run -d -p 3000:3000 sbetancurb/to-do-app-1:latest

    
